{% set name = "PyWavelets" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a12c7a6258c0015d2c75d88b87393ee015494551f049009e8b63eafed2d78efc

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - nose
  imports:
    - pywt

about:
  home: https://github.com/PyWavelets/pywt
  license: MIT
  license_file: LICENSE
  summary: 'Discrete Wavelet Transforms in Python'
  description: |
    PyWavelets is a free Open Source library for wavelet transforms in Python.
    Wavelets are mathematical basis functions that are localized in both time and frequency.
    Wavelet transforms are time-frequency transforms employing wavelets. They are similar to
    Fourier transforms, the difference being that Fourier transforms are localized only in
    frequency instead of in time and frequency.
  doc_url: http://pywavelets.readthedocs.io/en/latest/
  dev_url: https://github.com/PyWavelets/pywt
  doc_source_url: https://github.com/PyWavelets/pywt/tree/master/doc

extra:
  recipe-maintainers:
    - grlee77
    - jakirkham
    - ocefpaf
