{% set version = "1.0.0" %}

package:
  name: pywavelets
  version: {{ version }}

source:
  fn: PyWavelets-{{ version }}.tar.gz
  url: https://github.com/PyWavelets/pywt/archive/v{{ version }}.tar.gz
  sha256: 1696cbbbb74d670dda6bb75c0628fd1f82d98750661fcd9bd375082559252de8

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - numpy
    - setuptools
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - nose

about:
  home: https://github.com/PyWavelets/pywt
  license: MIT
  license_file: LICENSE
  summary: 'Discrete Wavelet Transforms in Python.'
  
  description: |
    PyWavelets is a free Open Source library for wavelet transforms in Python. 
    Wavelets are mathematical basis functions that are localized in both time and frequency. 
    Wavelet transforms are time-frequency transforms employing wavelets. They are similar to 
    Fourier transforms, the difference being that Fourier transforms are localized only in 
    frequency instead of in time and frequency.
  doc_url: http://pywavelets.readthedocs.io/en/latest/
  dev_url: https://github.com/PyWavelets/pywt
  doc_source_url: https://github.com/PyWavelets/pywt/tree/master/doc

extra:
  recipe-maintainers:
    - grlee77
    - jakirkham
    - ocefpaf
