{% set version = "1.0.0" %}

package:
  name: pywavelets
  version: {{ version }}

source:
  url: https://github.com/PyWavelets/pywt/archive/v{{ version }}.tar.gz
  sha256: 1696cbbbb74d670dda6bb75c0628fd1f82d98750661fcd9bd375082559252de8

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - nose
  imports:
    - pywt

about:
  home: https://github.com/PyWavelets/pywt
  license: MIT
  license_file: LICENSE
  summary: 'Discrete Wavelet Transforms in Python'

extra:
  recipe-maintainers:
    - grlee77
    - jakirkham
    - ocefpaf
