{% set version = "1.0.3" %}

package:
  name: pywavelets
  version: {{ version }}

source:
  url: https://github.com/PyWavelets/pywt/archive/v{{ version }}.tar.gz
  sha256: b152d4b551e3b454217c907e8722f7d8dc0adf104e6b3a8657d07e4020a990f2

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - nose
  imports:
    - pywt

about:
  home: https://github.com/PyWavelets/pywt
  license: MIT
  license_file: LICENSE
  summary: 'Discrete Wavelet Transforms in Python'

extra:
  recipe-maintainers:
    - grlee77
    - jakirkham
    - ocefpaf
