{% set version = "0.5.2" %}

package:
  name: pywavelets
  version: {{ version }}

source:
  fn: PyWavelets-{{ version }}.tar.gz
  url: https://github.com/PyWavelets/pywt/archive/v{{ version }}.tar.gz
  sha256: e36d629f40f7781da2dcaa2139bc476e9deaf91d79f675b5ce0bde6e775d1b53

build:
  number: 2
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - cython
    - numpy
    - setuptools
  build:
    - {{ compiler('c') }}
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - nose
  commands:
    - conda inspect linkages -p $PREFIX pywavelets  # [not win]
    - conda inspect objects -p $PREFIX pywavelets   # [osx]

about:
  home: https://github.com/PyWavelets/pywt
  license: MIT
  license_file: COPYING
  summary: 'Discrete Wavelet Transforms in Python.'
  
  description: |
    PyWavelets is a free Open Source library for wavelet transforms in Python. 
    Wavelets are mathematical basis functions that are localized in both time and frequency. 
    Wavelet transforms are time-frequency transforms employing wavelets. They are similar to 
    Fourier transforms, the difference being that Fourier transforms are localized only in 
    frequency instead of in time and frequency.
  doc_url: http://pywavelets.readthedocs.io/en/latest/
  dev_url: https://github.com/PyWavelets/pywt
  doc_source_url: https://github.com/PyWavelets/pywt/tree/master/doc

extra:
  recipe-maintainers:
    - grlee77
    - jakirkham
    - ocefpaf
