{% set name = "pywavelets" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 148d12203377772bea452a59211d98649c8ee4a05eff019a9021853a36babdc8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<311]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - meson-python >=0.18.0
    - cython >=3.0.4
    - numpy 2.0 # [py<313]
    - numpy 2.1 # [py>=313]
    - wheel
  run:
    - python
    - numpy >=1.25,<3
  run_constrained:
    - scipy >=1.9

test:
  imports:
    - pywt
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "import sys; import pywt; sys.exit(not pywt.test(verbose=2, label='full', tests=['pywt'], extra_argv=['--durations=50']))"

about:
  home: https://github.com/PyWavelets/pywt
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
  summary: Discrete Wavelet Transforms in Python
  description: |
    PyWavelets is a free Open Source library for wavelet transforms in Python.
    Wavelets are mathematical basis functions that are localized in both time and frequency.
    Wavelet transforms are time-frequency transforms employing wavelets. They are similar to
    Fourier transforms, the difference being that Fourier transforms are localized only in
    frequency instead of in time and frequency.
  doc_url: https://pywavelets.readthedocs.io
  dev_url: https://github.com/PyWavelets/pywt

extra:
  recipe-maintainers:
    - grlee77
    - jakirkham
    - ocefpaf
